name: interview_analyzer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0.1
  - numpy=1.24.3
  - pandas=2.0.1
  - matplotlib=3.7.1
  - pillow=9.5.0
  - scikit-learn=1.2.2
  - tensorflow=2.10.0
  - nltk=3.8.1
  - spacy=3.6.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - transformers=4.30.2
  - tqdm=4.65.0
  - opencv=4.7.0
  - dlib=19.24.2
  - mediapipe=0.10.1
  - pyaudio=0.2.13
  - librosa=0.10.0
  - kivy=2.2.1
  - pip:
    - deepface>=0.0.75
    - face-recognition>=1.3.0
    - soundfile>=0.10.3
    - speech_recognition>=3.8.1
    - pdfplumber>=0.9.0
    - python-docx>=0.8.11
    - docx2txt>=0.8
    - PyPDF2>=2.10.5
    - gensim>=4.3.0
    - customtkinter>=5.0.3
    - flask>=2.2.2
    - gunicorn>=20.1.0
    - pytesseract>=0.3.10
    - vaderSentiment>=3.3.2 